### ISSUE TITLE
Invalid header, charset is already set

### ISSUE THREAD

**Issue by mfairchild365** [unlcms/unl_fourone#10]
The framework already sets the content type and encoding, so the default one set by Drupal is both redundant and invalid. For example, see https://validator.w3.org/nu/?doc=http%3A%2F%2Fwdn.unl.edu%2F

This might be easily fixed by adding the following to `unl_fourone_html_head_alter()`:

```
unset($head_elements['system_meta_content_type']);
```

**Comment by ericras** [comment]
Fixed for 7
